USE [master]
GO

/****** Object:  Database [EcommerceCustomers]    Script Date: 2/06/2022 8:29:54 a. m. ******/
CREATE DATABASE [EcommerceCustomers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EcommerceCustomers', FILENAME = N'/var/opt/mssql/data/EcommerceCustomers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EcommerceCustomers_log', FILENAME = N'/var/opt/mssql/data/EcommerceCustomers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EcommerceCustomers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EcommerceCustomers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET ARITHABORT OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EcommerceCustomers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EcommerceCustomers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EcommerceCustomers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EcommerceCustomers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET RECOVERY FULL 
GO

ALTER DATABASE [EcommerceCustomers] SET  MULTI_USER 
GO

ALTER DATABASE [EcommerceCustomers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EcommerceCustomers] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EcommerceCustomers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EcommerceCustomers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EcommerceCustomers] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EcommerceCustomers] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EcommerceCustomers] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EcommerceCustomers] SET  READ_WRITE 
GO


